version: "3.3"
services:
  auth:
    image: test314zdes/mock-defender:auth
    # build:
    #   context: .
    #   dockerfile: ./services/auth/Dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env
    networks:
      - default_bd
    environment:
      - SERVICE_PORT=5000
      - SERVICE_NAME=auth

  faker:
    depends_on:
      - auth
    ports:
      - 5001:5000
    image: test314zdes/mock-defender:faker
    # build:
    #   context: .
    #   dockerfile: ./services/faker/Dockerfile
    env_file:
      - .env
    networks:
      - default_bd
    environment:
      - SERVICE_PORT=5000
      - SERVICE_NAME=faker

  client:
    restart: always
    depends_on:
      - auth
    networks:
      - default_bd
    image: test314zdes/mock-defender:client
    # build:
    #   context: .
    #   dockerfile: ./clients/front/Dockerfile
    environment:
      - SERVICE_PORT=3000
      - SERVICE_NAME=client

  server:
    depends_on:
      - auth
    restart: always
    image: nginx
    networks:
      - default_bd
    volumes:
      - ./server/default.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80

networks:
  default_bd:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.57.0/24
